### ISSUE TITLE
ERR! Exit status 1

### ISSUE THREAD

**Issue by MarkusKarlssonDevCode** [adamschwartz/docs-engine-example#1]
Hi Adam,
I would really like to try out the docs engine example locally, but when I build it from your instructions I get:

npm ERR! @ bootstrap: `node_modules/cloudflare-docs-engine/bin/commands.sh bootstrap`
npm ERR! Exit status 1

**Comment by adamschwartz** [comment]
Hey @MarkusKarlssonDevCode, if you `cd` to the `docs-engine-example` directory, can you `ls node_modules/cloudflare-docs-engine/bin/commands.sh`? (Is that file there?)

**Comment by MarkusKarlssonDevCode** [comment]
Hi @adamschwartz thank you for your reply.

Yes it is there. 

I am on windows, but that should not matter. Perhaps I just need to redo the cloning.
